export const products = [
  {
    id: "som-001",
    name: "Simple Buttermilk Masala",
    slug: "simple-buttermilk-masala",
    tag: "simple-buttermilk-masala",
    detail:
      "A classic and mild blend of spices perfect for making traditional, refreshing buttermilk — ideal for daily hydration and digestion.",
    image: "/assets/images/products/jeera_chass_masala.png",
    discription:
      "Enjoy the authentic taste of Somixa Simple Buttermilk Masala, made with a gentle mix of spices to bring out the natural flavor of buttermilk. This simple yet flavorful blend is designed to promote digestion and keep you refreshed throughout the day.",
    usability: ["Daily Refreshment", "Digestive Aid", "Cooling Drink"],
    specification: [
      "Mild Spice Blend",
      "Natural Ingredients",
      "No Artificial Additives",
    ],
  },
  {
    id: "som-002",
    name: "Pudina Masala",
    slug: "pudina-masala",
    tag: "pudina-masala",
    detail:
      "A refreshing pudina (mint) infused spice mix that adds a cool and invigorating flavor to your buttermilk.",
    image: "/assets/images/products/phudina_chass_masala.png",
    discription:
      "Somixa Pudina Masala combines the cooling essence of fresh mint with traditional spices to deliver a uniquely refreshing buttermilk experience. Perfect for hot weather and post-meal refreshment, this masala invigorates your palate and supports digestion naturally.",
    usability: ["Summer Drink", "Cooling Refreshment", "Post-Meal Aid"],
    specification: [
      "Mint-Infused Blend",
      "Cooling Effect",
      "Natural & Healthy",
    ],
  },
  {
    id: "som-003",
    name: "Dehydrated Tomato Powder",
    slug: "dehydrated-tomato-powder",
    tag: "dehydrated-tomato-powder",
    detail: "Pure and vibrant tomato powder made from sun-ripened tomatoes, perfect for soups, sauces, and seasoning.",
    image: "/assets/images/products/tomato.png",
    discription: "Somixa Dehydrated Tomato Powder captures the intense flavor and nutritional benefits of fresh tomatoes in a convenient, long-lasting form. Use it to add a rich tomato base to your culinary creations or as a tangy seasoning for snacks.",
    usability: ["Soup Base", "Sauces & Gravies", "Seasoning"],
    specification: ["100% Natural", "No Preservatives", "Rich in Lycopene"],
  },
  {
    id: "som-004",
    name: "Dehydrated Ginger Powder",
    slug: "dehydrated-ginger-powder",
    tag: "dehydrated-ginger-powder",
    detail: "Zesty and aromatic ginger powder, ideal for adding a warm kick to teas, bakes, and savory dishes.",
    image: "/assets/images/products/ginger.png",
    discription: "Somixa Dehydrated Ginger Powder is made from premium quality ginger roots, dried and ground to perfection. It offers a potent ginger flavor and numerous health benefits, making it an essential pantry staple for wellness and flavor.",
    usability: ["Ginger Tea", "Baking", "Savory Spicing"],
    specification: ["Premium Quality", "Zesty Aroma", "Digestive Health"],
  },
  {
    id: "som-005",
    name: "Dehydrated Curry Leaves Powder",
    slug: "dehydrated-curry-leaves-powder",
    tag: "dehydrated-curry-leaves-powder",
    detail: "Authentic and fragrant curry leaves powder, a must-have for traditional tempering and seasoning.",
    image: "/assets/images/products/curry_leaves.png",
    discription: "Experience the true essence of South Indian cuisine with Somixa Dehydrated Curry Leaves Powder. It retains the distinct aroma and earthy flavor of fresh curry leaves, perfect for adding to dals, curries, and chutneys.",
    usability: ["Tadka/Tempering", "Curry Flavoring", "Chutney Mix"],
    specification: ["Sun-Dried", "High Fragrance", "Nutrient-Rich"],
  },
  {
    id: "som-006",
    name: "Dehydrated Moringa Leaves Powder",
    slug: "dehydrated-moringa-leaves-powder",
    tag: "dehydrated-moringa-leaves-powder",
    detail: "Nutrient-dense moringa powder, a superfood addition for smoothies, juices, and health supplements.",
    image: "/assets/images/products/moringa_leaves.png",
    discription: "Somixa Dehydrated Moringa Leaves Powder is a powerhouse of vitamins and minerals. Known as a superfood, it can be easily incorporated into your daily diet by mixing it into drinks or sprinkling over meals for a nutritional boost.",
    usability: ["Smoothie Booster", "Health Drinks", "Food Fortification"],
    specification: ["Superfood Grade", "Cold-Dried", "Organic Source"],
  },
  {
    id: "som-007",
    name: "Dehydrated Lemon Powder",
    slug: "dehydrated-lemon-powder",
    tag: "dehydrated-lemon-powder",
    detail: "Tangy and refreshing lemon powder, perfect for instant lemonades, tea, and citrusy desserts.",
    image: "/assets/images/products/lemon.png",
    discription: "Somixa Dehydrated Lemon Powder offers the zest and tang of fresh lemons without the mess. It's perfect for quickly adding a citrusy flavor to your beverages, marinades, and baked goods, ensuring a consistent lemon taste every time.",
    usability: ["Instant Lemonade", "Citrus Flavoring", "Marinades"],
    specification: ["Tangy Zest", "Stable Shelf Life", "Pure Lemon Extract"],
  },
  {
    id: "som-008",
    name: "Dehydrated Orange Powder",
    slug: "dehydrated-orange-powder",
    tag: "dehydrated-orange-powder",
    detail: "Sweet and citrusy orange powder, ideal for flavoring desserts, beverages, and skincare applications.",
    image: "/assets/images/products/orange.png",
    discription: "Somixa Dehydrated Orange Powder is made from the zest and juice of high-quality oranges. It brings a bright, sweet, and tangy orange flavor to your desserts and drinks, and can even be used in DIY face masks for a natural glow.",
    usability: ["Beverage Flavoring", "Dessert Topping", "Skincare"],
    specification: ["Vitamin C Rich", "Sweet Citrus Aroma", "Natural Color"],
  },
  {
    id: "som-009",
    name: "Dehydrated Beetroot Powder",
    slug: "dehydrated-beetroot-powder",
    tag: "dehydrated-beetroot-powder",
    detail: "Vibrant and earthy beetroot powder, perfect as a natural food coloring and health supplement.",
    image: "/assets/images/products/beetroot.png",
    discription: "Somixa Dehydrated Beetroot Powder is a versatile ingredient that adds a beautiful deep red color and a subtle earthy sweetness to your food. It's packed with antioxidants and nitrates, making it great for pre-workout drinks and healthy bakes.",
    usability: ["Natural Coloring", "Pre-workout Mix", "Baking Color"],
    specification: ["Deep Vibrant Color", "Rich in Nitrates", "100% Pure"],
  },
  {
    id: "som-010",
    name: "Dehydrated Spinach (Palak) Powder",
    slug: "dehydrated-spinach-powder",
    tag: "dehydrated-spinach-powder",
    detail: "Mild and green spinach powder, an easy way to add greens to your pastas, doughs, and smoothies.",
    image: "/assets/images/products/spinch(palak).png",
    discription: "Somixa Dehydrated Spinach Powder allows you to enjoy the benefits of spinach in a highly concentrated form. It's perfect for sneaking more greens into your family's meals by adding it to pasta dough, rotis, or morning smoothies.",
    usability: ["Pasta/Noodle Dough", "Roti/Bread Mix", "Smoothie Green"],
    specification: ["Rich in Iron", "Mild Flavor", "Pure Greenery"],
  },
  {
    id: "som-011",
    name: "Dehydrated Carrot Powder",
    slug: "dehydrated-carrot-powder",
    tag: "dehydrated-carrot-powder",
    detail: "Sweet and nutritious carrot powder, great for baby food, soups, and adding natural sweetness to dishes.",
    image: "/assets/images/products/carrot.png",
    discription: "Somixa Dehydrated Carrot Powder is made from sweet, fresh carrots, providing a high concentration of Beta-Carotene. Its fine texture and natural sweetness make it an excellent addition to baby purees, soups, and healthy muffins.",
    usability: ["Baby Food", "Soup Thickener", "Baking Sweetener"],
    specification: ["Beta-Carotene Rich", "Natural Sweetness", "Finely Ground"],
  },
  {
    id: "som-012",
    name: "Dehydrated Mint Leaves Powder",
    slug: "dehydrated-mint-leaves-powder",
    tag: "dehydrated-mint-leaves-powder",
    detail: "Cool and refreshing mint powder, perfect for mocktails, chutneys, and flavoring yogurts.",
    image: "/assets/images/products/mint.png",
    discription: "Somixa Dehydrated Mint Leaves Powder captures the invigorating freshness of garden mint. It's a convenient way to add a cool minty flavor to your raitas, beverages, and spice blends, ensuring you always have mint on hand.",
    usability: ["Cooling Drinks", "Raita/Yogurt Mix", "Chutney Seasoning"],
    specification: ["Highly Refreshing", "Pudina Essence", "Shelf Stable"],
  },
];
